// Generated by npm run build:plugins. Edit this plugin's src/ modules.

// src-tauri/plugin_sources/shared/runtime.js
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
function clamp01(value) {
  const number = Number(value);
  return Number.isFinite(number) ? Math.max(0, Math.min(1, number)) : 0;
}
function createReconnectController({
  state,
  initialDelay,
  maximumDelay,
  idleDelay,
  hasConnection,
  connect,
  onFailure = () => {
  }
}) {
  const reset = () => {
    state.reconnectDelayMs = initialDelay;
  };
  const grow = () => {
    state.reconnectDelayMs = Math.min(maximumDelay, state.reconnectDelayMs * 2);
  };
  async function run() {
    while (!state.disposed) {
      let delay = idleDelay;
      if (!hasConnection() && !state.connecting && !state.disconnectedByUser && (state.autoConnect || state.manualConnectRequested)) {
        try {
          const connected = await connect();
          if (connected || hasConnection()) reset();
          else grow();
        } catch {
          if (state.disposed) return;
          state.connecting = false;
          onFailure();
          grow();
        }
        delay = state.reconnectDelayMs;
      } else {
        reset();
      }
      await sleep(delay);
    }
  }
  return { reset, grow, run };
}

// src-tauri/builtin_plugins/obs/src/protocol.js
var LOCAL_WRITE_QUIET_MS = 1200;
var FEEDBACK_INTENT_HOLD_MS = 1200;
var FEEDBACK_INTENT_MATCH_EPSILON = 0.02;
var VOLUME_WRITE_INTERVAL_MS = 16;
var VOLUME_WRITE_EPSILON = 2e-3;
var RECONNECT_INITIAL_DELAY_MS = 1e3;
var RECONNECT_MAX_DELAY_MS = 15e3;
var RECONNECT_IDLE_DELAY_MS = 5e3;
function rememberLocalMuteIntent(intents, inputName, muted, now = Date.now()) {
  if (!intents || !inputName) return;
  intents.set(String(inputName), {
    muted: Boolean(muted),
    at: now
  });
}
function forgetLocalMuteIntent(intents, inputName) {
  if (!intents || !inputName) return;
  intents.delete(String(inputName));
}
function shouldIgnoreLocalMuteEcho(intents, inputName, muted, now = Date.now()) {
  if (!intents || !inputName) return false;
  const key = String(inputName);
  const intent = intents.get(key);
  if (!intent) return false;
  if (now - Number(intent.at || 0) >= LOCAL_WRITE_QUIET_MS) {
    intents.delete(key);
    return false;
  }
  if (Boolean(intent.muted) !== Boolean(muted)) {
    intents.delete(key);
    return false;
  }
  return true;
}
function inputMuteFeedbackBindingIds(volumeBindings, muteBindings, inputName) {
  return /* @__PURE__ */ new Set([...volumeBindings?.get(inputName) || [], ...muteBindings?.get(inputName) || []]);
}
function bindingIntegrationTargets(binding) {
  const targets = Array.isArray(binding?.targets) ? [...binding.targets] : [];
  if (binding?.target != null) targets.push(binding.target);
  return targets.map((target) => target?.Integration || target?.integration).filter((target) => target && typeof target === "object");
}
function obsDisconnectedFeedbackUpdates(bindings) {
  const updates = /* @__PURE__ */ new Map();
  for (const binding of Array.isArray(bindings) ? bindings : []) {
    const bindingId = String(binding?.id || "").trim();
    if (!bindingId) continue;
    const obsTargets = bindingIntegrationTargets(binding).filter((target) => target.integration_id === "obs");
    if (obsTargets.length === 0) continue;
    const action = String(binding?.action || "Volume");
    if (action === "ToggleMute" || action === "ToggleEffect") {
      updates.set(`${bindingId}\0${action}`, { bindingId, action });
    }
    if (obsTargets.some((target) => target.kind === "input")) {
      updates.set(`${bindingId}\0ToggleMute`, { bindingId, action: "ToggleMute" });
    }
  }
  return Array.from(updates.values());
}
function sourceFilterKey(sourceName, filterName) {
  return `${String(sourceName || "")}\0${String(filterName || "")}`;
}
function normalizeSourceFilters(filters) {
  if (!Array.isArray(filters)) return [];
  return filters.map((filter) => {
    const filterName = String(filter?.filterName || "").trim();
    if (!filterName) return null;
    return {
      filterName,
      filterKind: String(filter?.filterKind || "").trim(),
      filterEnabled: Boolean(filter?.filterEnabled)
    };
  }).filter(Boolean);
}
function makeSourceFilterToggleTarget(sourceName, filterName) {
  return {
    Integration: {
      integration_id: "obs",
      kind: "source_filter",
      data: {
        source_name: String(sourceName),
        filter_name: String(filterName),
        action_kind: "stateful"
      }
    }
  };
}
function makeSourceFilterTargetOption(sourceName, filterName, iconDataUrl = null) {
  return {
    label: `${String(sourceName)} - ${String(filterName)}`,
    icon_data: iconDataUrl || null,
    kind: "integration-target",
    category: "integrations",
    target: makeSourceFilterToggleTarget(sourceName, filterName),
    description: "OBS source filter."
  };
}
function makeSourceFilterButtonAction(sourceName, filterName, iconDataUrl = null) {
  return {
    label: `Toggle ${String(filterName)}`,
    value: "ToggleEffect",
    behavior: "stateful",
    targetOption: makeSourceFilterTargetOption(sourceName, filterName, iconDataUrl)
  };
}
var obsTestUtils = {
  LOCAL_WRITE_QUIET_MS,
  rememberLocalMuteIntent,
  forgetLocalMuteIntent,
  shouldIgnoreLocalMuteEcho,
  inputMuteFeedbackBindingIds,
  obsDisconnectedFeedbackUpdates,
  sourceFilterKey,
  normalizeSourceFilters,
  makeSourceFilterToggleTarget,
  makeSourceFilterButtonAction
};
function isOsdWindow() {
  try {
    return new URLSearchParams(window.location.search).get("osd") === "1";
  } catch {
    return false;
  }
}
var ui = {
  statusText: null,
  statusDot: null,
  connectBtn: null,
  autoConnectInput: null,
  hostInput: null,
  portInput: null,
  passwordInput: null
};
function setStatus(connected, detail = "", opts = null) {
  const textEl = ui.statusText;
  const dotEl = ui.statusDot;
  const btn = ui.connectBtn;
  const connecting = opts && typeof opts === "object" ? Boolean(opts.connecting) : false;
  const disconnectedByUser = opts && typeof opts === "object" ? Boolean(opts.disconnectedByUser) : false;
  if (textEl) {
    textEl.textContent = connected ? detail || "Connected" : detail || "Not connected";
  }
  if (dotEl) {
    dotEl.classList.toggle("connected", Boolean(connected));
    dotEl.classList.toggle("connecting", !connected && connecting);
    dotEl.classList.toggle("error", !connected && !connecting && !disconnectedByUser);
  }
  if (btn) {
    if (connecting) {
      btn.disabled = true;
      btn.classList.add("disabled");
      btn.classList.remove("danger");
      btn.textContent = "Connecting...";
      return;
    }
    btn.disabled = false;
    btn.classList.remove("disabled");
    btn.classList.toggle("danger", Boolean(connected));
    btn.textContent = connected ? "Disconnect" : "Connect";
  }
}
async function sha256Base64(text) {
  const enc = new TextEncoder();
  const bytes = enc.encode(text);
  const hash = await crypto.subtle.digest("SHA-256", bytes);
  const arr = Array.from(new Uint8Array(hash));
  const bin = String.fromCharCode(...arr);
  return btoa(bin);
}
async function obsAuth(password, salt, challenge) {
  const secret = await sha256Base64(password + salt);
  return sha256Base64(secret + challenge);
}

// src-tauri/builtin_plugins/obs/src/connection_tab.js
function createConnectionTab({
  applyProfileSettings,
  connectOnce,
  ctx,
  iconDataUrl,
  loadObsSettingsFromStorage,
  queueDisconnectedFeedbackClear,
  saveObsSettingsToStorage,
  state
}) {
  function registerConnectionTab() {
    ctx.connections?.registerTab?.({
      id: "obs",
      name: "OBS Studio",
      icon_data: iconDataUrl || null,
      order: 10,
      mount: (container) => {
        container.innerHTML = `
        <div class="connection-item-header">
          <div class="connection-info">
            <img src="${iconDataUrl || ""}" alt="OBS" class="connection-icon" />
            <span class="connection-name">OBS Studio</span>
          </div>
          <div class="connection-status">
            <span class="connection-status-dot" data-role="dot"></span>
            <span data-role="text">Not connected</span>
          </div>
        </div>
        <div class="connection-content-wrapper">
          <div class="connection-grid">
            <div class="connection-row">
              <label>Host</label>
              <input data-role="host" type="text" placeholder="localhost" />
            </div>
            <div class="connection-row">
              <label>Password</label>
              <input data-role="password" type="password" placeholder="Optional" />
            </div>
            <div class="connection-row">
              <label>Port</label>
              <input data-role="port" type="number" value="4455" placeholder="4455" />
            </div>
          </div>
          <div class="connection-description">
            <p>Bind faders to OBS audio sources. Bind buttons to recording/stream actions, scene switching, and source visibility.</p>
          </div>
        </div>
        <div class="connection-footer">
          <button type="button" class="connection-button" data-role="connect">Connect</button>
          <div class="connection-row checkbox-row">
            <input type="checkbox" data-role="auto" id="obs-auto-connect" />
            <label for="obs-auto-connect">Auto connect</label>
          </div>
        </div>
      `;
        ui.statusText = container.querySelector('[data-role="text"]');
        ui.statusDot = container.querySelector('[data-role="dot"]');
        ui.hostInput = container.querySelector('[data-role="host"]');
        ui.portInput = container.querySelector('[data-role="port"]');
        ui.passwordInput = container.querySelector('[data-role="password"]');
        ui.connectBtn = container.querySelector('[data-role="connect"]');
        ui.autoConnectInput = container.querySelector('[data-role="auto"]');
        loadObsSettingsFromStorage();
        [ui.hostInput, ui.portInput, ui.passwordInput].forEach((el) => {
          el?.addEventListener("change", saveObsSettingsToStorage);
          el?.addEventListener("input", saveObsSettingsToStorage);
        });
        applyProfileSettings(ctx.profile?.get?.());
        if (ui.autoConnectInput) {
          ui.autoConnectInput.addEventListener("change", () => {
            const next = Boolean(ui.autoConnectInput.checked);
            applyProfileSettings({ auto_connect: next });
            try {
              const current = ctx.profile?.get?.() || {};
              ctx.profile?.set?.({ ...current, auto_connect: next });
            } catch {
            }
          });
        }
        if (ui.connectBtn) {
          ui.connectBtn.addEventListener("click", () => {
            if (state.connecting) return;
            if (state.connected) {
              state.disconnectedByUser = true;
              state.manualConnectRequested = false;
              try {
                state.ws?.close();
              } catch {
              }
              state.ws = null;
              state.connected = false;
              state.connecting = false;
              setStatus(false, "Disconnected", { disconnectedByUser: true });
              queueDisconnectedFeedbackClear().catch(() => {
              });
              return;
            }
            state.disconnectedByUser = false;
            state.manualConnectRequested = true;
            connectOnce().catch(() => {
              if (state.disposed) return;
              state.connecting = false;
              setStatus(false, "Not connected", { disconnectedByUser: state.disconnectedByUser });
            });
          });
        }
        setStatus(state.connected, state.connected ? "Connected" : "Not connected", {
          connecting: state.connecting,
          disconnectedByUser: state.disconnectedByUser
        });
      },
      unmount: () => {
        ui.statusText = null;
        ui.statusDot = null;
        ui.connectBtn = null;
        ui.autoConnectInput = null;
        ui.hostInput = null;
        ui.portInput = null;
        ui.passwordInput = null;
      }
    });
  }
  return { registerConnectionTab };
}

// src-tauri/builtin_plugins/obs/src/integration.js
function createIntegration({
  applyObsVolumeBatch,
  ctx,
  discoverAudioInputs,
  handleObsBindingTrigger,
  iconDataUrl,
  loadSourceFilterButtonActions,
  makeActionTarget,
  makeSceneTarget,
  makeSourceToggleTarget,
  momentaryAction,
  normalizeBatchTargets,
  obsActionKind,
  pendingVolumeWrites,
  refreshLists,
  request,
  resetAudioInputDiscovery,
  state,
  statefulAction,
  titleCaseAction
}) {
  function registerPluginIntegration() {
    ctx.registerIntegration({
      id: "obs",
      name: "OBS Studio",
      icon_data: iconDataUrl || null,
      buttonActions: [momentaryAction("Trigger", "Volume"), statefulAction("Toggle Mute", "ToggleMute")],
      describeTarget: (target) => {
        const t = target?.Integration || target?.integration;
        const data = t?.data || {};
        const icon_data = typeof data.icon_data === "string" && data.icon_data.trim() ? data.icon_data : iconDataUrl || null;
        let label = typeof data.label === "string" && data.label.trim() ? data.label : "";
        if (!label) {
          if (t?.kind === "input") label = String(data.input_name || "OBS Input");
          else if (t?.kind === "source") label = String(data.source_name || "Source");
          else if (t?.kind === "source_filter") {
            const sourceName = String(data.source_name || "Source");
            const filterName = String(data.filter_name || "Filter");
            label = `${sourceName} - ${filterName}`;
          } else if (t?.kind === "scene") label = String(data.scene_name || "OBS Scene");
          else if (t?.kind === "action") label = titleCaseAction(data.action || "Action");
          else label = "OBS Studio";
        }
        return { label: String(label), icon_data, ghost: !state.connected };
      },
      getTargetOptions: async (ctx2 = null) => {
        if (!state.connected) return [];
        const listChanged = await refreshLists();
        if (listChanged) {
          resetAudioInputDiscovery();
        }
        const controlType = ctx2 && typeof ctx2 === "object" ? ctx2.controlType : null;
        const nav = ctx2 && typeof ctx2 === "object" ? ctx2.nav : null;
        const opts = [];
        if (controlType === "fader") {
          if (!state.audioInputsReady) {
            await discoverAudioInputs();
          }
          for (const input of state.inputList) {
            const name = input?.inputName;
            if (!name) continue;
            if (state.audioInputsReady && !state.audioInputs.has(String(name))) {
              continue;
            }
            opts.push({
              label: String(name),
              icon_data: iconDataUrl || null,
              target: {
                Integration: { integration_id: "obs", kind: "input", data: { input_name: String(name) } }
              }
            });
          }
          if (opts.length === 0) {
            return [
              {
                label: "No compatible targets found for this control.",
                kind: "placeholder",
                ghost: true,
                icon_data: iconDataUrl || null,
                category: "integrations",
                suppressUnavailableTag: true
              }
            ];
          }
          return opts;
        }
        if (nav && nav.screen === "scene" && nav.sceneName) {
          const sceneName = String(nav.sceneName);
          opts.push({
            label: String(sceneName),
            icon_data: iconDataUrl || null,
            target: makeSceneTarget(sceneName),
            buttonActions: [momentaryAction("Switch Scene", "Volume")]
          });
          try {
            const list = await request("GetSceneItemList", { sceneName });
            const items = Array.isArray(list.sceneItems) ? list.sceneItems : [];
            for (const item of items) {
              const sourceName = item?.sourceName;
              if (!sourceName) continue;
              const buttonActions = [
                statefulAction("Toggle Visibility", "ToggleMute"),
                ...await loadSourceFilterButtonActions(sourceName)
              ];
              opts.push({
                label: String(sourceName),
                icon_data: iconDataUrl || null,
                target: makeSourceToggleTarget(sceneName, sourceName),
                buttonActions
              });
            }
          } catch {
          }
          return opts;
        }
        opts.push({ kind: "divider", label: "Actions" });
        const actions = [
          "ToggleRecord",
          "StartRecord",
          "StopRecord",
          "ToggleStream",
          "ToggleVirtualCam",
          "ToggleReplayBuffer",
          "ToggleStudioMode"
        ];
        for (const a of actions) {
          const actionKind = obsActionKind(a);
          opts.push({
            label: titleCaseAction(a),
            icon_data: iconDataUrl || null,
            target: makeActionTarget(a),
            buttonActions: [
              actionKind === "stateful" ? statefulAction(titleCaseAction(a), "Volume") : momentaryAction(titleCaseAction(a), "Volume")
            ]
          });
        }
        opts.push({ kind: "divider", label: "Scenes" });
        for (const scene of state.sceneList) {
          const name = scene?.sceneName;
          if (!name) continue;
          opts.push({
            label: String(name),
            icon_data: iconDataUrl || null,
            nav: { screen: "scene", sceneName: String(name) }
          });
        }
        opts.push({ kind: "divider", label: "Sources" });
        for (const input of state.inputList) {
          const name = input?.inputName;
          if (!name) continue;
          opts.push({
            label: String(name),
            icon_data: iconDataUrl || null,
            target: {
              Integration: { integration_id: "obs", kind: "input", data: { input_name: String(name) } }
            },
            buttonActions: [
              statefulAction("Toggle Mute", "ToggleMute"),
              ...await loadSourceFilterButtonActions(name)
            ]
          });
        }
        return opts;
      },
      onBindingTriggeredBatch: async (payload) => {
        if (!state.connected) return;
        if (payload?.action !== "Volume") return;
        try {
          const batchTargets = normalizeBatchTargets(payload);
          const inputTargets = batchTargets.filter((entry) => entry.target?.kind === "input");
          const otherTargets = batchTargets.filter((entry) => entry.target?.kind !== "input");
          if (inputTargets.length > 0) {
            applyObsVolumeBatch({
              ...payload,
              targets: inputTargets.map((entry) => ({
                target: entry.target,
                target_index: entry.targetIndex,
                target_count: entry.targetCount,
                is_primary_target: entry.isPrimaryTarget,
                original_target_index: entry.originalTargetIndex
              }))
            });
          }
          for (const entry of otherTargets) {
            await handleObsBindingTrigger({
              ...payload,
              target: entry.target,
              target_index: entry.targetIndex,
              target_count: entry.targetCount,
              is_primary_target: entry.isPrimaryTarget,
              original_target_index: entry.originalTargetIndex,
              momentary_trigger: entry.momentaryTrigger,
              button_event: entry.buttonEvent,
              button_action_kind: entry.buttonActionKind,
              button_input_active: entry.buttonInputActive
            });
          }
        } catch {
          pendingVolumeWrites.clear();
        }
      },
      onBindingTriggered: async (payload) => {
        try {
          await handleObsBindingTrigger(payload);
        } catch (e) {
          pendingVolumeWrites.clear();
        }
      }
    });
  }
  return { registerPluginIntegration };
}

// src-tauri/builtin_plugins/obs/src/actions.js
function createActions({
  applyObsVolumeBatch,
  buttonEvent,
  ctx,
  localMuteIntentByInput,
  obsActionKind,
  readStatefulActionValue,
  request,
  setMomentaryFeedback,
  state,
  statefulActionFeedback
}) {
  async function handleObsBindingTrigger(payload) {
    const bindingId = payload?.binding_id;
    const action = payload?.action;
    const value = payload?.value;
    const isPrimaryTarget = payload?.is_primary_target !== false;
    const targetIndex = Number(payload?.target_index ?? 0);
    const targetCount = Number(payload?.target_count ?? 1);
    const target = payload?.target || {};
    const kind = target.kind;
    const data = target.data || {};
    if (!state.connected) return;
    if (kind === "input") {
      const inputName = data.input_name;
      if (!inputName) return;
      if (action === "Volume") {
        applyObsVolumeBatch({
          binding_id: bindingId,
          action,
          value,
          targets: [
            {
              target,
              target_index: targetIndex,
              target_count: targetCount,
              is_primary_target: isPrimaryTarget
            }
          ]
        });
      } else if (action === "ToggleMute") {
        const muted = clamp01(value) > 0.5;
        rememberLocalMuteIntent(localMuteIntentByInput, inputName, muted);
        try {
          await request("SetInputMute", { inputName, inputMuted: muted });
        } catch (err) {
          forgetLocalMuteIntent(localMuteIntentByInput, inputName);
          throw err;
        }
        state.knownMutes.set(String(inputName), muted);
        if (bindingId) await ctx.feedback.set(bindingId, muted ? 1 : 0, action);
      }
      return;
    }
    if (kind === "action") {
      const a = data.action;
      if (!a) return;
      const stateful = String(data.action_kind || "").toLowerCase() === "stateful" || String(payload?.button_action_kind || "").toLowerCase() === "stateful" || obsActionKind(a) === "stateful";
      const eventKind = buttonEvent(payload);
      if (stateful) {
        if (eventKind !== "press") return;
      } else {
        if (eventKind === "release") {
          await setMomentaryFeedback(bindingId, action, false);
          return;
        }
        await setMomentaryFeedback(bindingId, action, true);
      }
      const map = {
        StartRecord: "StartRecord",
        StopRecord: "StopRecord",
        ToggleRecord: "ToggleRecord",
        ToggleStream: "ToggleStream",
        ToggleVirtualCam: "ToggleVirtualCam",
        ToggleReplayBuffer: "ToggleReplayBuffer"
      };
      let actionResponse = null;
      let expectedState = null;
      if (a === "ToggleStudioMode") {
        const cur = await request("GetStudioModeEnabled");
        expectedState = !Boolean(cur.studioModeEnabled);
        await request("SetStudioModeEnabled", { studioModeEnabled: expectedState });
      } else if (map[a]) {
        actionResponse = await request(map[a]);
      }
      if (stateful) {
        if (actionResponse && typeof actionResponse.outputActive === "boolean") {
          expectedState = actionResponse.outputActive;
        }
        if (expectedState == null) {
          await sleep(120);
        }
        const active = expectedState == null ? await readStatefulActionValue(a) : expectedState;
        const previous = bindingId ? statefulActionFeedback.get(bindingId) : void 0;
        const feedbackValue = active == null ? !Boolean(previous) : active;
        if (bindingId) statefulActionFeedback.set(bindingId, feedbackValue);
        if (bindingId) await ctx.feedback.set(bindingId, feedbackValue ? 1 : 0, action);
      }
      return;
    }
    if (kind === "scene") {
      const eventKind = buttonEvent(payload);
      if (eventKind === "release") {
        await setMomentaryFeedback(bindingId, action, false);
        return;
      }
      await setMomentaryFeedback(bindingId, action, true);
      const sceneName = data.scene_name;
      if (!sceneName) return;
      await request("SetCurrentProgramScene", { sceneName });
      state.currentScene = String(sceneName);
      return;
    }
    if (kind === "source") {
      const sceneName = data.scene_name;
      const sourceName = data.source_name;
      if (!sceneName || !sourceName) return;
      const list = await request("GetSceneItemList", { sceneName });
      const items = Array.isArray(list.sceneItems) ? list.sceneItems : [];
      const item = items.find((i) => i && i.sourceName === sourceName);
      if (!item) return;
      const enabled = clamp01(value) > 0.5;
      await request("SetSceneItemEnabled", {
        sceneName,
        sceneItemId: item.sceneItemId,
        sceneItemEnabled: enabled
      });
      if (bindingId) await ctx.feedback.set(bindingId, enabled ? 1 : 0, action);
      return;
    }
    if (kind === "source_filter") {
      const sourceName = data.source_name;
      const filterName = data.filter_name;
      if (!sourceName || !filterName) return;
      const enabled = clamp01(value) > 0.5;
      await request("SetSourceFilterEnabled", {
        sourceName,
        filterName,
        filterEnabled: enabled
      });
      if (bindingId) await ctx.feedback.set(bindingId, enabled ? 1 : 0, action);
      return;
    }
    if (kind === "media") {
      const eventKind = buttonEvent(payload);
      if (eventKind === "release") {
        await setMomentaryFeedback(bindingId, action, false);
        return;
      }
      await setMomentaryFeedback(bindingId, action, true);
      const inputName = data.source_name;
      const mediaAction = data.action;
      if (!inputName || !mediaAction) return;
      await request("TriggerMediaInputAction", { inputName, mediaAction });
    }
  }
  return { handleObsBindingTrigger };
}

// src-tauri/builtin_plugins/obs/src/connection.js
function createConnection({
  clearPendingRequests,
  ctx,
  lastSentVolumeByInput,
  localMuteIntentByInput,
  notifyTargetOptionsChanged,
  pending,
  pendingVolumeWrites,
  publishConnectionState,
  queueDisconnectedFeedbackClear,
  resetAudioInputDiscovery,
  scheduleListRefresh,
  shouldIgnoreBindingVolumeEcho,
  shouldIgnoreEcho,
  state,
  syncAllFeedback,
  syncSourceVisibilityForScene
}) {
  function nextRequestId() {
    state.requestId += 1;
    if (state.requestId > 1e6) state.requestId = 1;
    return state.requestId;
  }
  function getSettings() {
    let host = "localhost";
    let port = 4455;
    let password = "";
    try {
      const stored = localStorage.getItem("obsSettings");
      if (stored) {
        const parsed = JSON.parse(stored);
        if (parsed.host) host = String(parsed.host);
        if (parsed.port) port = Number(parsed.port);
        if (parsed.password != null) password = String(parsed.password);
      }
    } catch {
    }
    const hostEl = ui.hostInput;
    const portEl = ui.portInput;
    const passEl = ui.passwordInput;
    if (hostEl && hostEl.value) host = hostEl.value;
    if (portEl && portEl.value) port = Number(portEl.value);
    if (passEl && passEl.value != null) password = passEl.value;
    return { host, port, password };
  }
  function saveObsSettingsToStorage() {
    const current = getSettings();
    try {
      localStorage.setItem("obsSettings", JSON.stringify(current));
    } catch {
    }
  }
  function loadObsSettingsFromStorage() {
    let host = "localhost";
    let port = 4455;
    let password = "";
    try {
      const stored = localStorage.getItem("obsSettings");
      if (stored) {
        const parsed = JSON.parse(stored);
        if (parsed.host) host = String(parsed.host);
        if (parsed.port) port = Number(parsed.port);
        if (parsed.password != null) password = String(parsed.password);
      }
    } catch {
    }
    if (ui.hostInput) ui.hostInput.value = host;
    if (ui.portInput) ui.portInput.value = String(port);
    if (ui.passwordInput) ui.passwordInput.value = password;
  }
  async function send(msg) {
    if (!state.ws || state.ws.readyState !== WebSocket.OPEN) {
      throw new Error("OBS WebSocket not open");
    }
    state.ws.send(JSON.stringify(msg));
  }
  async function request(requestType, requestData = {}) {
    const id = String(nextRequestId());
    const payload = {
      op: 6,
      d: {
        requestType,
        requestId: id,
        requestData
      }
    };
    const p = new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        if (pending.has(id)) {
          const entry = pending.get(id);
          pending.delete(id);
          if (entry?.timer) clearTimeout(entry.timer);
          reject(new Error(`OBS request timed out: ${requestType}`));
        }
      }, 4e3);
      pending.set(id, { resolve, reject, timer });
    });
    await send(payload);
    return p;
  }
  async function refreshLists() {
    const previousInputs = state.inputList.map((i) => i?.inputName).filter(Boolean).map(String).sort().join("\n");
    const previousScenes = state.sceneList.map((s) => s?.sceneName).filter(Boolean).map(String).sort().join("\n");
    try {
      const inputs = await request("GetInputList");
      state.inputList = Array.isArray(inputs?.inputs) ? inputs.inputs : [];
    } catch {
    }
    try {
      const scenes = await request("GetSceneList");
      state.sceneList = Array.isArray(scenes?.scenes) ? scenes.scenes : [];
    } catch {
    }
    try {
      const cur = await request("GetCurrentProgramScene");
      state.currentScene = cur?.currentProgramSceneName || null;
    } catch {
    }
    const nextInputs = state.inputList.map((i) => i?.inputName).filter(Boolean).map(String).sort().join("\n");
    const nextScenes = state.sceneList.map((s) => s?.sceneName).filter(Boolean).map(String).sort().join("\n");
    return previousInputs !== nextInputs || previousScenes !== nextScenes;
  }
  async function discoverAudioInputs() {
    if (!state.connected) return;
    if (state.audioInputsDiscovering || state.audioInputsReady) return;
    state.audioInputsDiscovering = true;
    state.audioInputs = /* @__PURE__ */ new Set();
    const names = state.inputList.map((i) => i?.inputName).filter(Boolean).map((n) => String(n));
    const limit = 6;
    let idx = 0;
    const workers = new Array(limit).fill(0).map(async () => {
      while (idx < names.length) {
        const name = names[idx++];
        try {
          await request("GetInputVolume", { inputName: name });
          state.audioInputs.add(name);
        } catch {
        }
      }
    });
    try {
      await Promise.all(workers);
    } catch {
    }
    state.audioInputsReady = true;
    state.audioInputsDiscovering = false;
  }
  async function connectOnce() {
    if (state.disposed) return;
    const { host, port, password } = getSettings();
    const url = `ws://${host}:${port}`;
    state.connecting = true;
    setStatus(false, "Connecting...", { connecting: true });
    state.ws = new WebSocket(url);
    state.connected = false;
    state.ws.onmessage = async (ev) => {
      let msg;
      try {
        msg = JSON.parse(ev.data);
      } catch {
        return;
      }
      if (!msg || typeof msg !== "object") return;
      if (msg.op === 0) {
        const auth = msg.d?.authentication;
        const identify = {
          op: 1,
          d: {
            rpcVersion: 1,
            // Subscribe to all events so input volume/mute changes propagate.
            eventSubscriptions: 4294967295
          }
        };
        if (auth && auth.challenge && auth.salt && password) {
          identify.d.authentication = await obsAuth(password, auth.salt, auth.challenge);
        }
        await send(identify);
        return;
      }
      if (msg.op === 2) {
        state.connected = true;
        state.connecting = false;
        state.manualConnectRequested = false;
        setStatus(true, "Connected");
        await state.disconnectedFeedbackPromise.catch(() => {
        });
        await publishConnectionState(true);
        await refreshLists();
        resetAudioInputDiscovery();
        notifyTargetOptionsChanged();
        await discoverAudioInputs();
        notifyTargetOptionsChanged();
        await syncAllFeedback({ silent: true });
        return;
      }
      if (msg.op === 5) {
        const type = msg.d?.eventType;
        const data = msg.d?.eventData || {};
        if (type === "InputVolumeChanged") {
          if (data.inputName != null && data.inputVolumeMul != null) {
            const inputName = String(data.inputName);
            const vol = clamp01(data.inputVolumeMul);
            state.knownVolumes.set(inputName, vol);
            state.audioInputs.add(inputName);
            if (!shouldIgnoreEcho(inputName)) {
              const set = state.bindingsByInputVolume.get(inputName);
              if (set) {
                set.forEach((bid) => {
                  if (shouldIgnoreBindingVolumeEcho(bid, vol)) return;
                  ctx.feedback.set(bid, vol, "Volume", { silent: true }).catch(() => {
                  });
                });
              }
            }
          }
        }
        if (type === "InputMuteStateChanged") {
          if (data.inputName != null && data.inputMuted != null) {
            const inputName = String(data.inputName);
            const muted = Boolean(data.inputMuted);
            const ignoreLocalEcho = shouldIgnoreLocalMuteEcho(localMuteIntentByInput, inputName, muted);
            state.knownMutes.set(inputName, muted);
            if (!ignoreLocalEcho) {
              const muteFeedbackBindings = inputMuteFeedbackBindingIds(
                state.bindingsByInputVolume,
                state.bindingsByInputMute,
                inputName
              );
              muteFeedbackBindings.forEach((bid) => {
                ctx.feedback.set(bid, muted ? 1 : 0, "ToggleMute", { silent: true }).catch(() => {
                });
              });
            }
          }
        }
        if (type === "CurrentProgramSceneChanged") {
          if (data.sceneName != null) state.currentScene = String(data.sceneName);
        }
        if (type === "SceneItemEnableStateChanged" && data.sceneName != null) {
          syncSourceVisibilityForScene(String(data.sceneName), { silent: true }).catch(() => {
          });
        }
        if (type === "SourceFilterEnableStateChanged" && data.sourceName != null && data.filterName != null) {
          const sourceName = String(data.sourceName);
          const filterName = String(data.filterName);
          const set = state.bindingsBySourceFilter.get(sourceFilterKey(sourceName, filterName));
          if (set) {
            const enabled = Boolean(data.filterEnabled);
            set.forEach((action, bid) => {
              ctx.feedback.set(bid, enabled ? 1 : 0, action, { silent: true }).catch(() => {
              });
            });
          }
        }
        if (type === "InputCreated" || type === "InputRemoved" || type === "InputNameChanged" || type === "SceneCreated" || type === "SceneRemoved" || type === "SceneNameChanged" || type === "SceneItemCreated" || type === "SceneItemRemoved") {
          scheduleListRefresh(type);
        }
        if (type === "SourceFilterCreated" || type === "SourceFilterRemoved" || type === "SourceFilterNameChanged" || type === "SourceFilterListReindexed") {
          notifyTargetOptionsChanged();
        }
        return;
      }
      if (msg.op === 7) {
        const id = msg.d?.requestId;
        const entry = pending.get(id);
        if (!entry) return;
        if (entry?.timer) clearTimeout(entry.timer);
        pending.delete(id);
        const ok = msg.d?.requestStatus?.result;
        if (!ok) {
          entry.reject(new Error(msg.d?.requestStatus?.comment || "OBS request failed"));
          return;
        }
        entry.resolve(msg.d?.responseData || {});
      }
    };
    state.ws.onclose = () => {
      if (state.disposed) return;
      state.connected = false;
      state.connecting = false;
      setStatus(false, "Disconnected");
      state.ws = null;
      clearPendingRequests();
      pendingVolumeWrites.clear();
      lastSentVolumeByInput.clear();
      resetAudioInputDiscovery();
      notifyTargetOptionsChanged();
      queueDisconnectedFeedbackClear().catch(() => {
      });
    };
    state.ws.onerror = () => {
    };
    await sleep(250);
  }
  return {
    saveObsSettingsToStorage,
    loadObsSettingsFromStorage,
    request,
    refreshLists,
    discoverAudioInputs,
    connectOnce
  };
}

// src-tauri/builtin_plugins/obs/src/feedback.js
function createFeedback({ ctx, iconDataUrl, request, sourceVisibilityKey, state }) {
  function buttonEvent(payload) {
    const explicit = String(payload?.button_event || "").toLowerCase();
    if (explicit === "press" || explicit === "release") return explicit;
    if (payload?.momentary_trigger === false) return "release";
    if (payload?.momentary_trigger === true) return "press";
    return clamp01(payload?.value) > 0 ? "press" : "release";
  }
  async function setMomentaryFeedback(bindingId, action, active) {
    if (!bindingId) return;
    const value = active ? 1 : 0;
    await ctx.feedback.set(bindingId, value, action, { inputValue: value });
  }
  async function readStatefulActionValue(action) {
    try {
      if (action === "ToggleRecord") {
        const status = await request("GetRecordStatus");
        return Boolean(status?.outputActive);
      }
      if (action === "ToggleStream") {
        const status = await request("GetStreamStatus");
        return Boolean(status?.outputActive);
      }
      if (action === "ToggleVirtualCam") {
        const status = await request("GetVirtualCamStatus");
        return Boolean(status?.outputActive);
      }
      if (action === "ToggleReplayBuffer") {
        const status = await request("GetReplayBufferStatus");
        return Boolean(status?.outputActive);
      }
      if (action === "ToggleStudioMode") {
        const status = await request("GetStudioModeEnabled");
        return Boolean(status?.studioModeEnabled);
      }
    } catch {
      return null;
    }
    return null;
  }
  async function syncAllFeedback(opts = null) {
    if (!state.connected) return;
    const silent = opts && typeof opts === "object" ? Boolean(opts.silent) : true;
    const inputNames = /* @__PURE__ */ new Set([
      ...Array.from(state.bindingsByInputVolume.keys()),
      ...Array.from(state.bindingsByInputMute.keys())
    ]);
    for (const inputName of inputNames) {
      try {
        const [volRes, muteRes] = await Promise.all([
          request("GetInputVolume", { inputName }),
          request("GetInputMute", { inputName })
        ]);
        const vol = clamp01(volRes?.inputVolumeMul);
        const muted = Boolean(muteRes?.inputMuted);
        state.knownVolumes.set(String(inputName), vol);
        state.knownMutes.set(String(inputName), muted);
        const volBindings = state.bindingsByInputVolume.get(inputName);
        if (volBindings) {
          for (const bid of volBindings) {
            await ctx.feedback.set(bid, vol, "Volume", { silent });
          }
        }
        const muteFeedbackBindings = inputMuteFeedbackBindingIds(
          state.bindingsByInputVolume,
          state.bindingsByInputMute,
          inputName
        );
        for (const bid of muteFeedbackBindings) {
          await ctx.feedback.set(bid, muted ? 1 : 0, "ToggleMute", { silent });
        }
      } catch {
      }
    }
    const scenesWithVisibilityBindings = new Set(
      Array.from(state.bindingsBySourceVisibility.keys()).map((key) => key.split("\0")[0]).filter(Boolean)
    );
    for (const sceneName of scenesWithVisibilityBindings) {
      await syncSourceVisibilityForScene(sceneName, { silent });
    }
    const sourcesWithFilterBindings = new Set(
      Array.from(state.bindingsBySourceFilter.keys()).map((key) => key.split("\0")[0]).filter(Boolean)
    );
    for (const sourceName of sourcesWithFilterBindings) {
      await syncSourceFiltersForSource(sourceName, { silent });
    }
  }
  async function syncSourceVisibilityForScene(sceneName, opts = null) {
    if (!state.connected || !sceneName) return;
    const silent = opts && typeof opts === "object" ? Boolean(opts.silent) : true;
    try {
      const list = await request("GetSceneItemList", { sceneName });
      const items = Array.isArray(list.sceneItems) ? list.sceneItems : [];
      for (const item of items) {
        const sourceName = item?.sourceName;
        if (!sourceName) continue;
        const set = state.bindingsBySourceVisibility.get(sourceVisibilityKey(sceneName, sourceName));
        if (!set) continue;
        const enabled = Boolean(item.sceneItemEnabled);
        for (const bid of set) {
          await ctx.feedback.set(bid, enabled ? 1 : 0, "ToggleMute", { silent });
        }
      }
    } catch {
    }
  }
  async function syncSourceFiltersForSource(sourceName, opts = null) {
    if (!state.connected || !sourceName) return;
    const silent = opts && typeof opts === "object" ? Boolean(opts.silent) : true;
    try {
      const list = await request("GetSourceFilterList", { sourceName });
      const filters = normalizeSourceFilters(list?.filters);
      for (const filter of filters) {
        const set = state.bindingsBySourceFilter.get(sourceFilterKey(sourceName, filter.filterName));
        if (!set) continue;
        for (const [bid, action] of set.entries()) {
          await ctx.feedback.set(bid, filter.filterEnabled ? 1 : 0, action, { silent });
        }
      }
    } catch {
    }
  }
  async function loadSourceFilterButtonActions(sourceName) {
    if (!sourceName) return [];
    try {
      const filterList = await request("GetSourceFilterList", { sourceName: String(sourceName) });
      return normalizeSourceFilters(filterList?.filters).map(
        (filter) => makeSourceFilterButtonAction(String(sourceName), filter.filterName, iconDataUrl || null)
      );
    } catch {
      return [];
    }
  }
  return {
    buttonEvent,
    setMomentaryFeedback,
    readStatefulActionValue,
    syncAllFeedback,
    syncSourceVisibilityForScene,
    loadSourceFilterButtonActions
  };
}

// src-tauri/builtin_plugins/obs/src/volume.js
function createVolume({
  ctx,
  lastLocalWriteAt,
  lastSentVolumeByInput,
  localVolumeIntentByBinding,
  pendingVolumeWrites,
  request,
  state
}) {
  function shouldIgnoreEcho(inputName) {
    const t = lastLocalWriteAt.get(String(inputName)) || 0;
    return t > 0 && Date.now() - t < LOCAL_WRITE_QUIET_MS;
  }
  function rememberLocalVolumeIntent(bindingId, value) {
    if (!bindingId) return;
    localVolumeIntentByBinding.set(String(bindingId), {
      value: clamp01(value),
      at: Date.now()
    });
  }
  function shouldIgnoreBindingVolumeEcho(bindingId, confirmedValue) {
    if (!bindingId) return false;
    const key = String(bindingId);
    const intent = localVolumeIntentByBinding.get(key);
    if (!intent) return false;
    if (Date.now() - intent.at >= FEEDBACK_INTENT_HOLD_MS) {
      localVolumeIntentByBinding.delete(key);
      return false;
    }
    const delta = Math.abs(Number(confirmedValue) - Number(intent.value));
    return delta > FEEDBACK_INTENT_MATCH_EPSILON;
  }
  function normalizeBatchTargets(payload) {
    const rawTargets = Array.isArray(payload?.targets) ? payload.targets : [];
    return rawTargets.map((entry, index) => {
      const target = entry?.target || entry;
      if (!target || typeof target !== "object") return null;
      return {
        target,
        targetIndex: Number(entry?.target_index ?? index),
        targetCount: Number(entry?.target_count ?? rawTargets.length),
        isPrimaryTarget: entry?.is_primary_target === true,
        originalTargetIndex: Number(entry?.original_target_index ?? entry?.target_index ?? index),
        momentaryTrigger: entry?.momentary_trigger,
        buttonEvent: entry?.button_event,
        buttonActionKind: entry?.button_action_kind,
        buttonInputActive: entry?.button_input_active
      };
    }).filter(Boolean);
  }
  function scheduleVolumeFlush() {
    if (state.volumeFlushTimer) return;
    state.volumeFlushTimer = setTimeout(() => {
      state.volumeFlushTimer = null;
      flushVolumeWrites().catch(() => {
      });
    }, VOLUME_WRITE_INTERVAL_MS);
  }
  function queueVolumeWrite(inputName, volume) {
    const name = String(inputName || "");
    if (!name) return;
    const level = clamp01(volume);
    const pendingLevel = pendingVolumeWrites.get(name);
    if (typeof pendingLevel === "number" && Math.abs(pendingLevel - level) < VOLUME_WRITE_EPSILON) {
      return;
    }
    const lastSent = lastSentVolumeByInput.get(name);
    if (typeof lastSent === "number" && Math.abs(lastSent - level) < VOLUME_WRITE_EPSILON && !pendingVolumeWrites.has(name)) {
      return;
    }
    pendingVolumeWrites.set(name, level);
    scheduleVolumeFlush();
  }
  async function flushVolumeWrites() {
    if (state.volumeFlushInFlight) return;
    if (!state.connected || !state.ws || state.ws.readyState !== WebSocket.OPEN) {
      pendingVolumeWrites.clear();
      return;
    }
    state.volumeFlushInFlight = true;
    try {
      const writes = Array.from(pendingVolumeWrites.entries());
      pendingVolumeWrites.clear();
      if (!state.connected || !state.ws || state.ws.readyState !== WebSocket.OPEN || writes.length === 0) {
        return;
      }
      const sentAt = Date.now();
      for (const [inputName, level] of writes) {
        lastLocalWriteAt.set(String(inputName), sentAt);
        lastSentVolumeByInput.set(String(inputName), level);
      }
      await Promise.all(
        writes.map(
          ([inputName, level]) => request("SetInputVolume", {
            inputName,
            inputVolumeMul: level
          })
        )
      );
    } finally {
      state.volumeFlushInFlight = false;
      if (pendingVolumeWrites.size > 0) {
        scheduleVolumeFlush();
      }
    }
  }
  function applyObsVolumeBatch(payload) {
    const bindingId = payload?.binding_id;
    const value = payload?.value;
    const batchTargets = normalizeBatchTargets(payload);
    if (batchTargets.length === 0) return false;
    const vol = clamp01(value);
    let queuedAny = false;
    if (bindingId && batchTargets.some((entry) => entry.isPrimaryTarget)) {
      rememberLocalVolumeIntent(bindingId, vol);
      ctx.feedback.set(bindingId, vol, "Volume", { silent: false }).catch(() => {
      });
    }
    for (const entry of batchTargets) {
      const target = entry.target;
      if (target.kind !== "input") continue;
      const inputName = target.data?.input_name;
      if (!inputName) continue;
      state.knownVolumes.set(String(inputName), vol);
      queueVolumeWrite(inputName, vol);
      queuedAny = true;
    }
    if (queuedAny) {
      flushVolumeWrites().catch(() => {
      });
    }
    return queuedAny;
  }
  return { shouldIgnoreEcho, shouldIgnoreBindingVolumeEcho, normalizeBatchTargets, applyObsVolumeBatch };
}

// src-tauri/builtin_plugins/obs/src/targets.js
function createTargets({}) {
  function titleCaseAction(a) {
    const map = {
      ToggleRecord: "Toggle Recording",
      StartRecord: "Start Recording",
      StopRecord: "Stop Recording",
      ToggleStream: "Toggle Streaming",
      ToggleVirtualCam: "Toggle Virtual Camera",
      ToggleReplayBuffer: "Toggle Replay Buffer",
      ToggleStudioMode: "Toggle Studio Mode"
    };
    return map[a] || a;
  }
  function momentaryAction(label, value = "Volume") {
    return { label, value, behavior: "momentary" };
  }
  function statefulAction(label, value = "ToggleMute") {
    return { label, value, behavior: "stateful" };
  }
  function obsActionKind(action) {
    return String(action || "").startsWith("Toggle") ? "stateful" : "momentary";
  }
  function makeActionTarget(action) {
    return {
      Integration: {
        integration_id: "obs",
        kind: "action",
        data: { action, action_kind: obsActionKind(action) }
      }
    };
  }
  function makeSceneTarget(sceneName) {
    return {
      Integration: {
        integration_id: "obs",
        kind: "scene",
        data: { scene_name: String(sceneName), action_kind: "momentary" }
      }
    };
  }
  function makeSourceToggleTarget(sceneName, sourceName) {
    return {
      Integration: {
        integration_id: "obs",
        kind: "source",
        data: {
          scene_name: String(sceneName),
          source_name: String(sourceName),
          action_kind: "stateful"
        }
      }
    };
  }
  function sourceVisibilityKey(sceneName, sourceName) {
    return `${String(sceneName || "")}\0${String(sourceName || "")}`;
  }
  return {
    titleCaseAction,
    momentaryAction,
    statefulAction,
    obsActionKind,
    makeActionTarget,
    makeSceneTarget,
    makeSourceToggleTarget,
    sourceVisibilityKey
  };
}

// src-tauri/builtin_plugins/obs/src/bindings.js
function createBindings({
  ctx,
  discoverAudioInputs,
  queueDisconnectedFeedbackClear,
  refreshLists,
  sourceVisibilityKey,
  state,
  syncAllFeedback
}) {
  function readBindings() {
    try {
      const all = ctx.bindings?.getAll?.();
      return Array.isArray(all) ? all : [];
    } catch {
      return [];
    }
  }
  function setBindings(next) {
    state.bindings = Array.isArray(next) ? next : [];
    rebuildBindingIndex();
    if (!state.connected) {
      queueDisconnectedFeedbackClear().catch(() => {
      });
    }
  }
  function notifyTargetOptionsChanged() {
    try {
      ctx.app?.invalidateBindingsUI?.();
    } catch {
    }
    try {
      window.dispatchEvent(
        new CustomEvent("midimaster:integration-targets-changed", {
          detail: { integrationId: "obs" }
        })
      );
    } catch {
    }
  }
  function resetAudioInputDiscovery() {
    state.audioInputs = /* @__PURE__ */ new Set();
    state.audioInputsReady = false;
    state.audioInputsDiscovering = false;
  }
  function scheduleListRefresh(reason = "") {
    if (!state.connected) return;
    if (state.listRefreshTimer) {
      clearTimeout(state.listRefreshTimer);
    }
    state.listRefreshTimer = setTimeout(
      () => {
        state.listRefreshTimer = null;
        (async () => {
          await refreshLists();
          resetAudioInputDiscovery();
          notifyTargetOptionsChanged();
          await discoverAudioInputs();
          notifyTargetOptionsChanged();
          await syncAllFeedback({ silent: true });
        })().catch(() => {
        });
      },
      reason === "connected" ? 0 : 250
    );
  }
  function rebuildBindingIndex() {
    state.bindingsByInputVolume = /* @__PURE__ */ new Map();
    state.bindingsByInputMute = /* @__PURE__ */ new Map();
    state.bindingsBySourceVisibility = /* @__PURE__ */ new Map();
    state.bindingsBySourceFilter = /* @__PURE__ */ new Map();
    for (const b of state.bindings) {
      const t = b?.target?.Integration || b?.target?.integration;
      if (!t || t.integration_id !== "obs") continue;
      const action = b.action || "Volume";
      if (t.kind === "input") {
        const inputName = t.data?.input_name;
        if (!inputName) continue;
        if (action === "Volume") {
          if (!state.bindingsByInputVolume.has(inputName))
            state.bindingsByInputVolume.set(inputName, /* @__PURE__ */ new Set());
          state.bindingsByInputVolume.get(inputName).add(b.id);
        }
        if (action === "ToggleMute") {
          if (!state.bindingsByInputMute.has(inputName)) state.bindingsByInputMute.set(inputName, /* @__PURE__ */ new Set());
          state.bindingsByInputMute.get(inputName).add(b.id);
        }
      }
      if (t.kind === "source" && action === "ToggleMute") {
        const sceneName = t.data?.scene_name;
        const sourceName = t.data?.source_name;
        if (!sceneName || !sourceName) continue;
        const key = sourceVisibilityKey(sceneName, sourceName);
        if (!state.bindingsBySourceVisibility.has(key)) state.bindingsBySourceVisibility.set(key, /* @__PURE__ */ new Set());
        state.bindingsBySourceVisibility.get(key).add(b.id);
      }
      if (t.kind === "source_filter" && (action === "ToggleMute" || action === "ToggleEffect")) {
        const sourceName = t.data?.source_name;
        const filterName = t.data?.filter_name;
        if (!sourceName || !filterName) continue;
        const key = sourceFilterKey(sourceName, filterName);
        if (!state.bindingsBySourceFilter.has(key)) state.bindingsBySourceFilter.set(key, /* @__PURE__ */ new Map());
        state.bindingsBySourceFilter.get(key).set(b.id, action);
      }
    }
  }
  return {
    readBindings,
    setBindings,
    notifyTargetOptionsChanged,
    resetAudioInputDiscovery,
    scheduleListRefresh
  };
}

// src-tauri/builtin_plugins/obs/src/index.js
async function activate(ctx) {
  const DEFAULT_AUTO_CONNECT = true;
  let iconDataUrl = null;
  try {
    iconDataUrl = await ctx.assets?.readDataUrl?.("OBSLogo.png", "image/png");
  } catch {
    iconDataUrl = null;
  }
  if (isOsdWindow()) {
    ctx.registerIntegration({
      id: "obs",
      describeTarget: (target) => {
        const t = target?.Integration || target?.integration;
        const data = t?.data || {};
        if (t?.kind === "input") {
          return { label: data.input_name || "OBS Input", icon_data: iconDataUrl || null };
        }
        if (t?.kind === "scene") {
          return { label: data.scene_name || "OBS Scene", icon_data: iconDataUrl || null };
        }
        return { label: "OBS Studio", icon_data: iconDataUrl || null };
      },
      getTargetOptions: () => [],
      onBindingTriggeredBatch: async () => {
      },
      onBindingTriggered: async () => {
      }
    });
    return;
  }
  ui.invalidateBindingsUI = ctx.app?.invalidateBindingsUI;
  const state = {
    ws: null,
    connected: false,
    connecting: false,
    disposed: false,
    requestId: 1,
    inputList: [],
    sceneList: [],
    listRefreshTimer: null,
    knownVolumes: /* @__PURE__ */ new Map(),
    knownMutes: /* @__PURE__ */ new Map(),
    currentScene: null,
    audioInputs: /* @__PURE__ */ new Set(),
    audioInputsReady: false,
    audioInputsDiscovering: false,
    bindings: [],
    bindingsByInputVolume: /* @__PURE__ */ new Map(),
    bindingsByInputMute: /* @__PURE__ */ new Map(),
    bindingsBySourceVisibility: /* @__PURE__ */ new Map(),
    bindingsBySourceFilter: /* @__PURE__ */ new Map(),
    volumeFlushTimer: null,
    volumeFlushInFlight: false,
    disconnectedFeedbackPromise: Promise.resolve(),
    autoConnect: DEFAULT_AUTO_CONNECT,
    manualConnectRequested: false,
    disconnectedByUser: false,
    reconnectDelayMs: RECONNECT_INITIAL_DELAY_MS
  };
  const reconnect = createReconnectController({
    state,
    initialDelay: RECONNECT_INITIAL_DELAY_MS,
    maximumDelay: RECONNECT_MAX_DELAY_MS,
    idleDelay: RECONNECT_IDLE_DELAY_MS,
    hasConnection: () => Boolean(state.connected),
    connect: () => connectOnce(),
    onFailure: () => setStatus(false, "Not connected", { disconnectedByUser: state.disconnectedByUser })
  });
  const resetReconnectBackoff = reconnect.reset;
  const pending = /* @__PURE__ */ new Map();
  const statefulActionFeedback = /* @__PURE__ */ new Map();
  const lastLocalWriteAt = /* @__PURE__ */ new Map();
  const localMuteIntentByInput = /* @__PURE__ */ new Map();
  const localVolumeIntentByBinding = /* @__PURE__ */ new Map();
  const pendingVolumeWrites = /* @__PURE__ */ new Map();
  const lastSentVolumeByInput = /* @__PURE__ */ new Map();
  function publishConnectionState(nextConnected) {
    try {
      return Promise.resolve(ctx.integration?.setConnected?.("obs", Boolean(nextConnected)));
    } catch {
      return Promise.resolve();
    }
  }
  function queueDisconnectedFeedbackClear() {
    statefulActionFeedback.clear();
    state.disconnectedFeedbackPromise = state.disconnectedFeedbackPromise.catch(() => {
    }).then(async () => {
      if (state.connected) return;
      await publishConnectionState(false);
      if (state.connected) return;
      const updates = obsDisconnectedFeedbackUpdates(state.bindings);
      await Promise.allSettled(
        updates.map(
          ({ bindingId, action }) => ctx.feedback.set(bindingId, 0, action, {
            silent: true,
            forceHardwareFeedback: true
          })
        )
      );
    });
    return state.disconnectedFeedbackPromise;
  }
  function clearPendingRequests(errorMessage = null) {
    for (const entry of pending.values()) {
      if (entry?.timer) clearTimeout(entry.timer);
      if (errorMessage && typeof entry?.reject === "function") {
        try {
          entry.reject(new Error(errorMessage));
        } catch {
        }
      }
    }
    pending.clear();
  }
  function clearRuntimeTimers() {
    if (state.listRefreshTimer) {
      clearTimeout(state.listRefreshTimer);
      state.listRefreshTimer = null;
    }
    if (state.volumeFlushTimer) {
      clearTimeout(state.volumeFlushTimer);
      state.volumeFlushTimer = null;
    }
  }
  function closeSocketForDispose() {
    const current = state.ws;
    state.ws = null;
    if (!current) return;
    try {
      current.onopen = null;
      current.onmessage = null;
      current.onclose = null;
      current.onerror = null;
      current.close();
    } catch {
    }
  }
  function disposeObsRuntime() {
    state.disposed = true;
    state.connected = false;
    state.connecting = false;
    state.manualConnectRequested = false;
    clearRuntimeTimers();
    closeSocketForDispose();
    clearPendingRequests("OBS plugin disposed");
    pendingVolumeWrites.clear();
    lastSentVolumeByInput.clear();
    state.knownVolumes.clear();
    state.knownMutes.clear();
    statefulActionFeedback.clear();
    lastLocalWriteAt.clear();
    localMuteIntentByInput.clear();
    localVolumeIntentByBinding.clear();
    resetAudioInputDiscovery();
    return queueDisconnectedFeedbackClear();
  }
  const {
    readBindings,
    setBindings,
    notifyTargetOptionsChanged,
    resetAudioInputDiscovery,
    scheduleListRefresh
  } = createBindings({
    ctx,
    discoverAudioInputs: (...args) => discoverAudioInputs(...args),
    queueDisconnectedFeedbackClear,
    refreshLists: (...args) => refreshLists(...args),
    sourceVisibilityKey: (...args) => sourceVisibilityKey(...args),
    state,
    syncAllFeedback: (...args) => syncAllFeedback(...args)
  });
  const {
    titleCaseAction,
    momentaryAction,
    statefulAction,
    obsActionKind,
    makeActionTarget,
    makeSceneTarget,
    makeSourceToggleTarget,
    sourceVisibilityKey
  } = createTargets({});
  const { shouldIgnoreEcho, shouldIgnoreBindingVolumeEcho, normalizeBatchTargets, applyObsVolumeBatch } = createVolume({
    ctx,
    lastLocalWriteAt,
    lastSentVolumeByInput,
    localVolumeIntentByBinding,
    pendingVolumeWrites,
    request: (...args) => request(...args),
    state
  });
  const {
    buttonEvent,
    setMomentaryFeedback,
    readStatefulActionValue,
    syncAllFeedback,
    syncSourceVisibilityForScene,
    loadSourceFilterButtonActions
  } = createFeedback({
    ctx,
    iconDataUrl,
    request: (...args) => request(...args),
    sourceVisibilityKey,
    state
  });
  const {
    saveObsSettingsToStorage,
    loadObsSettingsFromStorage,
    request,
    refreshLists,
    discoverAudioInputs,
    connectOnce
  } = createConnection({
    clearPendingRequests,
    ctx,
    lastSentVolumeByInput,
    localMuteIntentByInput,
    notifyTargetOptionsChanged,
    pending,
    pendingVolumeWrites,
    publishConnectionState,
    queueDisconnectedFeedbackClear,
    resetAudioInputDiscovery,
    scheduleListRefresh,
    shouldIgnoreBindingVolumeEcho,
    shouldIgnoreEcho,
    state,
    syncAllFeedback,
    syncSourceVisibilityForScene
  });
  const { handleObsBindingTrigger } = createActions({
    applyObsVolumeBatch,
    buttonEvent,
    ctx,
    localMuteIntentByInput,
    obsActionKind,
    readStatefulActionValue,
    request,
    setMomentaryFeedback,
    state,
    statefulActionFeedback
  });
  ctx.lifecycle?.onDispose?.(disposeObsRuntime);
  function applyProfileSettings(settings) {
    const next = settings && typeof settings === "object" && "auto_connect" in settings ? Boolean(settings.auto_connect) : DEFAULT_AUTO_CONNECT;
    state.autoConnect = next;
    if (!next) {
      state.manualConnectRequested = false;
      state.disconnectedByUser = true;
    }
    if (ui.autoConnectInput) {
      ui.autoConnectInput.checked = next;
    }
    if (next && !state.connected && !state.connecting) {
      state.manualConnectRequested = true;
      state.disconnectedByUser = false;
      resetReconnectBackoff();
    }
  }
  try {
    applyProfileSettings(ctx.profile?.get?.());
    ctx.profile?.onChanged?.((ev) => {
      if (state.disposed) return;
      applyProfileSettings(ev?.settings || ev);
    });
  } catch {
  }
  reconnect.run();
  const { registerPluginIntegration } = createIntegration({
    applyObsVolumeBatch,
    ctx,
    discoverAudioInputs,
    handleObsBindingTrigger,
    iconDataUrl,
    loadSourceFilterButtonActions,
    makeActionTarget,
    makeSceneTarget,
    makeSourceToggleTarget,
    momentaryAction,
    normalizeBatchTargets,
    obsActionKind,
    pendingVolumeWrites,
    refreshLists,
    request,
    resetAudioInputDiscovery,
    state,
    statefulAction,
    titleCaseAction
  });
  registerPluginIntegration();
  setBindings(readBindings());
  ctx.bindings?.onChanged?.((next) => {
    if (state.disposed) return;
    setBindings(next);
    syncAllFeedback({ silent: true }).catch(() => {
    });
  });
  const { registerConnectionTab } = createConnectionTab({
    applyProfileSettings,
    connectOnce,
    ctx,
    iconDataUrl,
    loadObsSettingsFromStorage,
    queueDisconnectedFeedbackClear,
    saveObsSettingsToStorage,
    state
  });
  registerConnectionTab();
}
export {
  activate,
  obsTestUtils
};
