export const APPEARANCE_THEME_FILE_KIND = "midimaster.appearance.theme.v1";

export const DEFAULT_FONT_FAMILY = "bahnschrift";

export const DEFAULT_FONT_SIZE = 14;

export const DEFAULT_TEXT_RENDERING = "auto";

export const FONT_STACKS = {
  bahnschrift: {
    label: "Bahnschrift",
    labelKey: "settings.appearance.fontBahnschrift",
    stack: '"Bahnschrift", "Aptos", "Segoe UI", sans-serif',
  },
  aptos: {
    label: "Aptos",
    labelKey: "settings.appearance.fontAptos",
    stack: '"Aptos", "Segoe UI", sans-serif',
  },
  segoe: {
    label: "Segoe UI",
    labelKey: "settings.appearance.fontSegoe",
    stack: '"Segoe UI", "Aptos", sans-serif',
  },
  inter: {
    label: "Inter",
    labelKey: "settings.appearance.fontInter",
    stack: '"Inter", "Segoe UI", "Aptos", sans-serif',
  },
  mono: {
    label: "Monospace",
    labelKey: "settings.appearance.fontMono",
    stack: '"Cascadia Mono", "Consolas", monospace',
  },
};

export const TEXT_RENDERING_MODES = {
  auto: {
    label: "Auto",
    labelKey: "settings.appearance.renderingAuto",
    value: "auto",
  },
  legibility: {
    label: "Optimize Legibility",
    labelKey: "settings.appearance.renderingLegibility",
    value: "optimizeLegibility",
  },
  geometric: {
    label: "Geometric Precision",
    labelKey: "settings.appearance.renderingGeometric",
    value: "geometricPrecision",
  },
  speed: {
    label: "Optimize Speed",
    labelKey: "settings.appearance.renderingSpeed",
    value: "optimizeSpeed",
  },
};

export const BUILT_IN_PRESETS = {
  system: {
    id: "system",
    labelKey: "settings.appearance.presetSystem",
    scheme: "system",
    accentColor: "#5aa7ff",
    iconColor: "#5aa7ff",
    tintColor: "#172334",
    base: "dark",
    preview: ["#5aa7ff", "#5bd28a"],
  },
  dark: {
    id: "dark",
    labelKey: "settings.appearance.presetDark",
    scheme: "dark",
    accentColor: "#5aa7ff",
    iconColor: "#5aa7ff",
    tintColor: "#172334",
    base: "dark",
    preview: ["#5aa7ff", "#7fbfff"],
  },
  light: {
    id: "light",
    labelKey: "settings.appearance.presetLight",
    scheme: "light",
    accentColor: "#2f78d4",
    iconColor: "#2f78d4",
    tintColor: "#e8f1fa",
    base: "light",
    preview: ["#2f78d4", "#55b7ec"],
  },
  midnight: {
    id: "midnight",
    labelKey: "settings.appearance.presetMidnight",
    scheme: "dark",
    accentColor: "#8b6dff",
    iconColor: "#8b6dff",
    tintColor: "#242044",
    base: "midnight",
    preview: ["#8b6dff", "#6f5cff"],
  },
  ocean: {
    id: "ocean",
    labelKey: "settings.appearance.presetOcean",
    scheme: "dark",
    accentColor: "#24c8d6",
    iconColor: "#24c8d6",
    tintColor: "#123642",
    base: "ocean",
    preview: ["#24c8d6", "#47a7ff"],
  },
  forest: {
    id: "forest",
    labelKey: "settings.appearance.presetForest",
    scheme: "dark",
    accentColor: "#69c95a",
    iconColor: "#69c95a",
    tintColor: "#1e3324",
    base: "forest",
    preview: ["#69c95a", "#9bd35a"],
  },
  sunset: {
    id: "sunset",
    labelKey: "settings.appearance.presetSunset",
    scheme: "dark",
    accentColor: "#f0a12d",
    iconColor: "#f0a12d",
    tintColor: "#3a241f",
    base: "sunset",
    preview: ["#f0a12d", "#f25c61"],
  },
};

export const BASE_PALETTES = {
  dark: {
    appBg: "#0b1017",
    sidebarBg: "#0e151d",
    topbarBg: "#101722",
    surface: "#151c24",
    surfaceRaised: "#111820",
    surfaceMuted: "#18212b",
    surfaceSubtle: "#101720",
    controlBg: "#111820",
    controlBgHover: "#151d27",
    controlBorder: "#303945",
    controlBorderStrong: "#3a4654",
    textPrimary: "#f3f6fb",
    textSecondary: "#c8d1dd",
    textMuted: "#929daa",
    danger: "#ff6268",
    success: "#5bd28a",
    chipBg: "#182334",
    chipBorder: "#33445b",
    chipText: "#e8f1ff",
    sliderTrack: "#2b3948",
    sliderThumb: "#f3f6fb",
    overlayBg: "rgba(7, 10, 14, 0.72)",
  },
  light: {
    appBg: "#eef3f8",
    sidebarBg: "#e5edf5",
    topbarBg: "#f6f9fc",
    surface: "#f8fbfe",
    surfaceRaised: "#ffffff",
    surfaceMuted: "#edf4fa",
    surfaceSubtle: "#f2f7fb",
    controlBg: "#fbfdff",
    controlBgHover: "#eef5fb",
    controlBorder: "#c4d0dd",
    controlBorderStrong: "#aab8c8",
    textPrimary: "#172230",
    textSecondary: "#344457",
    textMuted: "#6e7d8e",
    danger: "#c7353c",
    success: "#2f9b61",
    chipBg: "#eaf3fc",
    chipBorder: "#c7d8eb",
    chipText: "#17385c",
    sliderTrack: "#d1dbe7",
    sliderThumb: "#f8fbfe",
    overlayBg: "rgba(23, 34, 48, 0.36)",
  },
  midnight: {
    appBg: "#0b0c17",
    sidebarBg: "#10101f",
    topbarBg: "#121323",
    surface: "#181827",
    surfaceRaised: "#11111e",
    surfaceMuted: "#1c1d30",
    surfaceSubtle: "#10101c",
    controlBg: "#131422",
    controlBgHover: "#1b1c2f",
    controlBorder: "#363650",
    controlBorderStrong: "#464665",
    textPrimary: "#f7f4ff",
    textSecondary: "#d5cef0",
    textMuted: "#9c94b6",
    danger: "#ff657e",
    success: "#65d49c",
    chipBg: "#211e35",
    chipBorder: "#454066",
    chipText: "#f0ebff",
    sliderTrack: "#34344d",
    sliderThumb: "#fbf9ff",
    overlayBg: "rgba(8, 8, 18, 0.74)",
  },
  ocean: {
    appBg: "#061318",
    sidebarBg: "#071920",
    topbarBg: "#09202a",
    surface: "#10262e",
    surfaceRaised: "#0b1d24",
    surfaceMuted: "#12313b",
    surfaceSubtle: "#081820",
    controlBg: "#0c2028",
    controlBgHover: "#12303a",
    controlBorder: "#254b57",
    controlBorderStrong: "#32616f",
    textPrimary: "#effcff",
    textSecondary: "#c5e9f0",
    textMuted: "#87aeb7",
    danger: "#ff646b",
    success: "#54d8aa",
    chipBg: "#12313a",
    chipBorder: "#315c68",
    chipText: "#e7fbff",
    sliderTrack: "#244651",
    sliderThumb: "#effcff",
    overlayBg: "rgba(4, 12, 16, 0.74)",
  },
  forest: {
    appBg: "#0a130e",
    sidebarBg: "#0d1912",
    topbarBg: "#112018",
    surface: "#16251b",
    surfaceRaised: "#101b14",
    surfaceMuted: "#1a2d20",
    surfaceSubtle: "#0e1812",
    controlBg: "#111e16",
    controlBgHover: "#1a2d20",
    controlBorder: "#334a38",
    controlBorderStrong: "#415d48",
    textPrimary: "#f3fbf4",
    textSecondary: "#d0e7d2",
    textMuted: "#94aa98",
    danger: "#ff685f",
    success: "#73d365",
    chipBg: "#1a2d20",
    chipBorder: "#3e5d44",
    chipText: "#effbef",
    sliderTrack: "#314735",
    sliderThumb: "#f5fff6",
    overlayBg: "rgba(5, 12, 8, 0.74)",
  },
  sunset: {
    appBg: "#170f10",
    sidebarBg: "#1d1414",
    topbarBg: "#241819",
    surface: "#2a1d1d",
    surfaceRaised: "#201616",
    surfaceMuted: "#342322",
    surfaceSubtle: "#1a1212",
    controlBg: "#221818",
    controlBgHover: "#322322",
    controlBorder: "#58403a",
    controlBorderStrong: "#6d5048",
    textPrimary: "#fff7f1",
    textSecondary: "#eed5c4",
    textMuted: "#b59a8d",
    danger: "#ff5d62",
    success: "#79d190",
    chipBg: "#35221f",
    chipBorder: "#674d43",
    chipText: "#fff3ea",
    sliderTrack: "#563d36",
    sliderThumb: "#fff7f1",
    overlayBg: "rgba(15, 8, 8, 0.74)",
  },
};

export const TOKEN_TO_VAR = {
  appBg: "--app-bg",
  sidebarBg: "--sidebar-bg",
  topbarBg: "--topbar-bg",
  surface: "--surface",
  surfaceRaised: "--surface-raised",
  surfaceMuted: "--surface-muted",
  surfaceSubtle: "--surface-subtle",
  controlBg: "--control-bg",
  controlBgHover: "--control-bg-hover",
  controlBorder: "--control-border",
  controlBorderIntensity: "--control-border-intensity",
  controlBorderStrong: "--control-border-strong",
  textPrimary: "--text-primary",
  textPrimaryIntensity: "--text-primary-intensity",
  textSecondary: "--text-secondary",
  textMuted: "--text-muted",
  themeTint: "--theme-tint",
  themeTintIntensity: "--theme-tint-intensity",
  iconColor: "--icon-color",
  iconColorIntensity: "--icon-color-intensity",
  logoFilter: "--app-logo-filter",
  logoGlow: "--app-logo-glow",
  accent: "--accent",
  accentIntensity: "--accent-intensity",
  accentSoft: "--accent-soft",
  danger: "--danger",
  dangerSoft: "--danger-soft",
  success: "--success",
  successSoft: "--success-soft",
  shadowRaised: "--shadow-raised",
  chipBg: "--chip-bg",
  chipBorder: "--chip-border",
  chipText: "--chip-text",
  sliderTrack: "--slider-track",
  sliderFill: "--slider-fill",
  sliderThumb: "--slider-thumb",
  overlayBg: "--overlay-bg",
  accentStrong: "--accent-strong",
};

export const CSS_TOKEN_KEYS = new Set(Object.values(TOKEN_TO_VAR));

export const USER_TOKEN_KEYS = new Set([
  "accentIntensity",
  "themeTint",
  "themeTintIntensity",
  "controlBorder",
  "controlBorderIntensity",
  "textPrimary",
  "textPrimaryIntensity",
  "iconColor",
  "iconColorIntensity",
]);

export const INTENSITY_TOKEN_KEYS = new Set([
  "accentIntensity",
  "themeTintIntensity",
  "controlBorderIntensity",
  "textPrimaryIntensity",
  "iconColorIntensity",
]);
export const BUILT_IN_IDS = new Set(Object.keys(BUILT_IN_PRESETS));
