/** Public DOM reference names and their element IDs. */
export const DOM_REF_IDS = Object.freeze({
  midiSelect: "midi-device",
  midiOutputSelect: "midi-output-device",
  midiStatus: "midi-status",
  refreshMidiButton: "refresh-midi",
  learnBindingButton: "learn-binding",
  bindingAddFooterButton: "binding-add-footer-button",
  sessionsContainer: "sessions",
  profileDropdown: "profiles-dropdown",
  profileToggle: "profile-toggle",
  profileCurrent: "profile-current",
  profileList: "profile-list",
  profilePageList: "profile-page-list",
  profilePageCreateInput: "profile-page-create-input",
  profilePageCreateButton: "profile-page-create-button",
  profilePageImportButton: "profile-page-import",
  profilePageExportCurrentButton: "profile-page-export-current",
  bindingsContainer: "bindings",
  bindingTypeFilter: "binding-type-filter",
  bindingSearchInput: "binding-search",
  bindingDensityToggle: "binding-density-toggle",
  mainScreen: "main-screen",
  sidebarCollapseToggle: "sidebar-collapse-toggle",
  targetPanel: "target-panel",
  targetPanelList: "target-panel-list",
  targetPanelTitle: "target-panel-title",
  targetPanelClose: "target-panel-close",
  targetPanelBack: "target-panel-back",
  bindingConfigPanel: "binding-config-panel",
  bindingConfigBack: "binding-config-back",
  bindingConfigTitle: "binding-config-title",
  bindingConfigClose: "binding-config-close",
  bindingConfigCancel: "binding-config-cancel",
  bindingConfigSave: "binding-config-save",
  bindingConfigName: "binding-config-name",
  bindingConfigButtonLightSection: "binding-config-button-light-section",
  bindingConfigButtonLightSelectRow: "binding-config-button-light-select-row",
  bindingConfigButtonLightSelect: "binding-config-button-light-select",
  bindingConfigIndicatorCustom: "binding-config-indicator-custom",
  bindingConfigIndicatorMsgType: "binding-config-indicator-msg-type",
  bindingConfigIndicatorChannel: "binding-config-indicator-channel",
  bindingConfigIndicatorController: "binding-config-indicator-controller",
  bindingConfigIndicatorLearn: "binding-config-indicator-learn",
  bindingConfigIndicatorClear: "binding-config-indicator-clear",
  bindingConfigButtonLearnSection: "binding-config-button-learn-section",
  bindingConfigButtonLearnButton: "binding-config-button-learn-button",
  bindingConfigButtonLearnIndicator: "binding-config-button-learn-indicator",
  bindingConfigButtonLearnStatus: "binding-config-button-learn-status",
  bindingConfigMacroSummarySection: "binding-config-macro-summary-section",
  bindingConfigMacroSummary: "binding-config-macro-summary",
  bindingConfigMacroEdit: "binding-config-macro-edit",
  bindingConfigMacroSection: "binding-config-macro-section",
  bindingConfigMacroList: "binding-config-macro-list",
  bindingConfigMacroAddAction: "binding-config-macro-add-action",
  bindingConfigMacroAddWait: "binding-config-macro-add-wait",
  bindingConfigMacroAddParallel: "binding-config-macro-add-parallel",
  bindingConfigSoundboardSection: "binding-config-soundboard-section",
  bindingConfigSoundboardFile: "binding-config-soundboard-file",
  bindingConfigSoundboardStatus: "binding-config-soundboard-status",
  bindingConfigSoundboardReplace: "binding-config-soundboard-replace",
  bindingConfigSoundboardPreview: "binding-config-soundboard-preview",
  bindingConfigSoundboardPlaybackTime: "binding-config-soundboard-playback-time",
  bindingConfigSoundboardWaveform: "binding-config-soundboard-waveform",
  bindingConfigSoundboardStart: "binding-config-soundboard-start",
  bindingConfigSoundboardEnd: "binding-config-soundboard-end",
  bindingConfigSoundboardStartTime: "binding-config-soundboard-start-time",
  bindingConfigSoundboardEndTime: "binding-config-soundboard-end-time",
  bindingConfigSoundboardSelectionTime: "binding-config-soundboard-selection-time",
  bindingConfigSoundboardVolume: "binding-config-soundboard-volume",
  bindingConfigSoundboardVolumeValue: "binding-config-soundboard-volume-value",
  bindingConfigSoundboardSpeed: "binding-config-soundboard-speed",
  bindingConfigSoundboardSpeedValue: "binding-config-soundboard-speed-value",
  bindingConfigSoundboardOutput: "binding-config-soundboard-output",
  bindingConfigSoundboardMonitor: "binding-config-soundboard-monitor",
  bindingConfigSoundboardVirtualMicOption: "binding-config-soundboard-virtual-mic-option",
  bindingConfigSoundboardVirtualMicHelp: "binding-config-soundboard-virtual-mic-help",
  bindingConfigSoundboardVirtualMic: "binding-config-soundboard-virtual-mic",
  bindingConfigCurveSection: "binding-config-curve-section",
  bindingConfigFeedbackOutputSection: "binding-config-feedback-output-section",
  bindingConfigFeedbackOutputCustom: "binding-config-feedback-output-custom",
  bindingConfigFeedbackMsgType: "binding-config-feedback-msg-type",
  bindingConfigFeedbackChannel: "binding-config-feedback-channel",
  bindingConfigFeedbackController: "binding-config-feedback-controller",
  bindingConfigFeedbackLearn: "binding-config-feedback-learn",
  bindingConfigFeedbackClear: "binding-config-feedback-clear",
  bindingConfigMuteSection: "binding-config-mute-section",
  bindingConfigAssignSection: "binding-config-assign-section",
  bindingConfigMuteLabel: "binding-config-mute-label",
  bindingConfigMuteLearn: "binding-config-mute-learn",
  bindingConfigMuteClear: "binding-config-mute-clear",
  bindingConfigMuteModeRoot: "binding-config-mute-mode-root",
  bindingConfigMuteModeButton: "binding-config-mute-mode-button",
  bindingConfigMuteModeMenu: "binding-config-mute-mode-menu",
  bindingConfigMuteModeToggle: "binding-config-mute-mode-toggle",
  bindingConfigMuteModeValue: "binding-config-mute-mode-value",
  bindingConfigAssignLabel: "binding-config-assign-label",
  bindingConfigAssignLearn: "binding-config-assign-learn",
  bindingConfigAssignClear: "binding-config-assign-clear",
  bindingConfigAssignModeRoot: "binding-config-assign-mode-root",
  bindingConfigAssignModeButton: "binding-config-assign-mode-button",
  bindingConfigAssignModeMenu: "binding-config-assign-mode-menu",
  bindingConfigAssignModeAdd: "binding-config-assign-mode-add",
  bindingConfigAssignModeReplace: "binding-config-assign-mode-replace",
  bindingConfigAssignModeClear: "binding-config-assign-mode-clear",
  bindingConfigCurveCards: "binding-config-curve-cards",
  bindingConfigCurveHelp: "binding-config-curve-help",
  bindingConfigCurvePresetRoot: "binding-config-curve-preset-root",
  bindingConfigCurvePresetButton: "binding-config-curve-preset-button",
  bindingConfigCurvePresetMenu: "binding-config-curve-preset-menu",
  bindingConfigCurvePresetSearch: "binding-config-curve-preset-search",
  bindingConfigCurvePresetList: "binding-config-curve-preset-list",
  bindingConfigCurvePresetSave: "binding-config-curve-preset-save",
  bindingConfigCurvePresetForm: "binding-config-curve-preset-form",
  bindingConfigCurvePresetFormTitle: "binding-config-curve-preset-form-title",
  bindingConfigCurvePresetName: "binding-config-curve-preset-name",
  bindingConfigCurvePresetFormSave: "binding-config-curve-preset-form-save",
  bindingConfigCurvePresetFormCancel: "binding-config-curve-preset-form-cancel",
  bindingConfigCustomEditor: "binding-config-custom-editor",
  bindingConfigCustomSurface: "binding-config-custom-surface",
  bindingConfigCustomReset: "binding-config-custom-reset",
  bindingConfigAssignHelp: "binding-config-assign-help",
  bindingConfigPreviewLearnShell: "binding-config-preview-learn-shell",
  bindingConfigPreviewLearnButton: "binding-config-preview-learn-button",
  bindingConfigPreviewLearnIndicator: "binding-config-preview-learn-indicator",
  bindingConfigPreviewLearnStatus: "binding-config-preview-learn-status",
  bindingConfigPreviewTargetIcon: "binding-config-preview-target-icon",
  bindingConfigPreviewTargetLabel: "binding-config-preview-target-label",
  bindingConfigPreviewTargetTags: "binding-config-preview-target-tags",
  bindingConfigPreviewFill: "binding-config-preview-fill",
  bindingConfigPreviewThumb: "binding-config-preview-thumb",
  bindingConfigPreviewButton: "binding-config-preview-button",
  bindingConfigPreviewButtonFace: "binding-config-preview-button-face",
  bindingConfigPreviewButtonLabel: "binding-config-preview-button-label",
  bindingConfigPreviewValue: "binding-config-preview-value",
  bindingConfigPreviewStatus: "binding-config-preview-status",
  bindingConfigPreviewMainMidi: "binding-config-preview-main-midi",
  bindingConfigPreviewMuteRow: "binding-config-preview-mute-row",
  bindingConfigPreviewMute: "binding-config-preview-mute",
  bindingConfigPreviewAssignRow: "binding-config-preview-assign-row",
  bindingConfigPreviewAssign: "binding-config-preview-assign",
  bindingConfigPreviewCurveRow: "binding-config-preview-curve-row",
  bindingConfigPreviewCurve: "binding-config-preview-curve",
  bindingConfigPreviewMidiValue: "binding-config-preview-midi-value",
  learnPanel: "learn-panel",
  learnPanelTitle: "learn-panel-title",
  learnPanelMessage: "learn-panel-message",
  learnPanelSpinner: "learn-panel-spinner",
  learnPanelActions: "learn-panel-actions",
  learnPanelCancel: "learn-panel-cancel",
  learnPanelConfirm: "learn-panel-confirm",
  learnPanelClose: "learn-panel-close",
  settingsButton: "settings-button",
  topbarUpdateButton: "topbar-update-button",
  settingsPanel: "settings-panel",
  settingsPanelClose: "settings-panel-close",
  connectionsButton: "connections-button",
  connectionsPanel: "connections-panel",
  connectionsPanelClose: "connections-panel-close",
  connectionsSidebar: "connections-sidebar",
  connectionsContent: "connections-content",
  osdEnabledToggle: "osd-enabled",
  osdMonitorSelect: "osd-monitor",
  osdLabelModeSelect: "osd-label-mode",
  osdStyleSelect: "osd-style",
  osdTransparencyInput: "osd-transparency",
  osdTransparencyValue: "osd-transparency-value",
  osdScaleInput: "osd-scale",
  osdScaleValue: "osd-scale-value",
  osdPositionPicker: "osd-position-picker",
  virtualAudioPanel: "virtual-audio-panel",
  virtualAudioInstall: "virtual-audio-install",
  virtualAudioUpdate: "virtual-audio-update",
  virtualAudioUpdateNotice: "virtual-audio-update-notice",
  virtualAudioRepair: "virtual-audio-repair",
  virtualAudioProblemRepair: "virtual-audio-problem-repair",
  virtualAudioRemove: "virtual-audio-remove",
  virtualAudioRestart: "virtual-audio-restart",
  virtualAudioRestartLater: "virtual-audio-restart-later",
  virtualAudioCopyDiagnostics: "virtual-audio-copy-diagnostics",
  virtualAudioEnabled: "virtual-audio-enabled",
  virtualAudioRoutingError: "virtual-audio-routing-error",
  virtualAudioInputDevice: "virtual-audio-input-device",
  virtualAudioMicrophoneGain: "virtual-audio-microphone-gain",
  virtualAudioMicrophoneGainValue: "virtual-audio-microphone-gain-value",
  virtualAudioSoundboardGain: "virtual-audio-soundboard-gain",
  virtualAudioSoundboardGainValue: "virtual-audio-soundboard-gain-value",
  virtualAudioMicrophoneMeter: "virtual-audio-microphone-meter",
  virtualAudioSoundboardMeter: "virtual-audio-soundboard-meter",
  virtualAudioOutputMeter: "virtual-audio-output-meter",
  virtualAudioLimiterMeter: "virtual-audio-limiter-meter",
  virtualAudioLimiterValue: "virtual-audio-limiter-value",
  virtualAudioDriverVersion: "virtual-audio-driver-version",
  virtualAudioServiceStatus: "virtual-audio-service-status",
  virtualAudioEndpointStatus: "virtual-audio-endpoint-status",
  virtualAudioProblemMessage: "virtual-audio-problem-message",
  startWithWindowsSelect: "start-with-windows",
  startInTraySelect: "start-in-tray",
  minimizeToTraySelect: "minimize-to-tray",
  exitToTraySelect: "exit-to-tray",
  languageSelect: "language-select",
  autoCheckUpdatesButton: "auto-check-updates-button",
  midiDeviceInventoryConsentToggle: "midi-device-inventory-consent-toggle",
  openLogsFolderButton: "open-logs-folder",
  resetAppDataButton: "reset-app-data",
  checkForUpdatesButton: "check-for-updates",
  settingsUpdateStatus: "settings-update-status",
  updateCurrentVersion: "update-current-version",
  updateLatestVersion: "update-latest-version",
  sidebarAppVersion: "sidebar-app-version",
  osd: "volume-osd",
  alertOverlay: "alert-overlay",
  alertTitle: "alert-title",
  alertMessage: "alert-message",
  alertClose: "alert-close",
  alertSecondary: "alert-secondary",
  alertCancel: "alert-cancel",
  alertOk: "alert-ok",
});

function selectRefs(refs, { prefixes = [], keys = [] }) {
  const namedKeys = new Set(keys);
  return Object.fromEntries(
    Object.entries(refs).filter(([key]) => (
      namedKeys.has(key) || prefixes.some((prefix) => key.startsWith(prefix))
    )),
  );
}

function findIdRefs(documentSource) {
  return Object.fromEntries(
    Object.entries(DOM_REF_IDS).map(([key, id]) => [key, documentSource.getElementById(id)]),
  );
}

/**
 * Creates feature-scoped DOM namespaces.
 * @param {Document} [documentSource]
 */
export function createDomRefs(documentSource = document) {
  const all = {
    ...findIdRefs(documentSource),
    appShell: documentSource.querySelector(".app-shell"),
    sidebarNav: documentSource.querySelector(".sidebar-nav"),
    appPages: Array.from(documentSource.querySelectorAll("[data-page-panel]")),
    appNavItems: Array.from(documentSource.querySelectorAll("[data-page]")),
  };

  return {
    shell: selectRefs(all, {
      prefixes: ["app", "sidebar"],
      keys: ["mainScreen", "sessionsContainer", "osd"],
    }),
    bindings: selectRefs(all, {
      prefixes: ["binding", "learn"],
      keys: ["mainScreen"],
    }),
    targets: selectRefs(all, { prefixes: ["target"] }),
    midi: selectRefs(all, {
      prefixes: ["midi", "learn"],
      keys: ["mainScreen", "refreshMidiButton", "bindingAddFooterButton"],
    }),
    profiles: selectRefs(all, { prefixes: ["profile"] }),
    settings: selectRefs(all, {
      prefixes: ["settings", "osd", "virtualAudio"],
      keys: [
        "settingsButton",
        "topbarUpdateButton",
        "startWithWindowsSelect",
        "startInTraySelect",
        "minimizeToTraySelect",
        "exitToTraySelect",
        "languageSelect",
        "autoCheckUpdatesButton",
        "midiDeviceInventoryConsentToggle",
        "openLogsFolderButton",
        "resetAppDataButton",
        "checkForUpdatesButton",
        "updateCurrentVersion",
        "updateLatestVersion",
        "sidebarAppVersion",
      ],
    }),
    connections: selectRefs(all, { prefixes: ["connections"] }),
    alerts: selectRefs(all, { prefixes: ["alert"] }),
  };
}
