import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { bundledPlugins } from "./lib/bundled_plugins.mjs";

const check = process.argv.includes("--check");
for (const plugin of await bundledPlugins()) {
  const destination = new URL(plugin.entry, plugin.directory);
  const result = await build({
    absWorkingDir: fileURLToPath(new URL("../", import.meta.url)),
    entryPoints: [fileURLToPath(new URL("src/index.js", plugin.directory))],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2022",
    charset: "utf8",
    minify: false,
    write: false,
    banner: { js: "// Generated by npm run build:plugins. Edit this plugin's src/ modules." },
  });
  const generated = result.outputFiles[0].text;
  if (check) {
    if ((await readFile(destination, "utf8")) !== generated) {
      throw new Error(`${plugin.id}: plugin.mjs is stale; run npm run build:plugins`);
    }
  } else {
    await writeFile(destination, generated);
  }
  console.log(`${plugin.id}: ${check ? "verified" : "generated"}`);
}
